---
runtime_options: 
  user_id: jar335
  write_locally: False
  

dependency_info:
  IRS-PUF:
    vintage: 2023091310
    scenario: historical
    
  DINA: 
    vintage: 2023082913
    scenario: historical
    
  Compiled-SOI-Tables:
    vintage: 2023100323
    scenario: historical
  
  Macro-Projections: 
    vintage: 2024100910
    scenario: baseline
    
  CPS-ASEC:
    vintage: 2024110517
    scenario: historical
    
  SCF:
    vintage: 2022
    scenario: historical
  
  SIPP:
    vintage: 2024090311
    scenario: baseline
  
