---
runtime_options: 
  user_id: jar335
  write_locally: False
  

dependency_info:
  IRS-PUF:
    vintage: 2023091310
    scenario: historical
    
  DINA: 
    vintage: 2023082913
    scenario: historical
    
  Compiled-SOI-Tables:
    vintage: 2023100323
    scenario: historical
  
  Macro-Projections: 
    vintage: 2024061815
    scenario: baseline
    
  CPS-ASEC:
    vintage: 2024010721
    scenario: historical
    
  CPS-ASEC-Panel:
    vintage: 2024013021
    scenario: historical

  
